Updated flatpak-builder - 1.2.3-2

diff --git a/world/flatpak-builder/PKGBUILD b/world/flatpak-builder/PKGBUILD
--- a/world/flatpak-builder/PKGBUILD
+++ b/world/flatpak-builder/PKGBUILD
@@ -1,17 +1,18 @@
 # Maintainer: Jan Alexander Steffens (heftig) <heftig@archlinux.org>
 
 pkgname=flatpak-builder
-pkgver=1.2.3
-pkgrel=2
+pkgver=1.4.0
+pkgrel=1
 pkgdesc="Tool to build flatpaks from source"
 url="https://flatpak.org"
 arch=(x86_64)
-license=(LGPL)
+license=(LGPL-2.1-or-later)
 depends=(
-  appstream-glib
+  appstream
   binutils
   breezy
   cpio
+  debugedit
   elfutils
   flatpak
   fuse3
@@ -25,22 +26,20 @@ makedepends=(
   docbook-xsl
   git
   gobject-introspection
+  meson
   xmlto
 )
 checkdepends=(valgrind)
 replaces=('flatpak<0.9.10')
-options=(debug)
-_commit=d7dbc51267e83242a9fe0d5a7b5304db0ac72f4f  # tags/1.2.3
+_commit=7d621d6eec7fe523c68d46f3853cdc86561b5637  # tags/1.4.0^0
 source=(
   "git+https://github.com/flatpak/flatpak-builder#commit=$_commit"
   "git+https://gitlab.gnome.org/GNOME/libglnx.git"
-  "git+https://sourceware.org/git/debugedit.git"
   fusermount3.diff
 )
 b2sums=('SKIP'
         'SKIP'
-        'SKIP'
-        '8598941ac5ba4eab8e8e6adf1f6d43c4c161a4283335554ed03e968698c4f7326afc9b2c7d01cc3185ab05e889fc2220e459c156c10cd130edaae89bddf08979')
+        '7d54ba89b3481722026ef556aabfc8b157069701ec89e900a5616899b937eacc077e620fb2a5f9d4faf5f7189414bc25e9a0fc57a0d8d2952bb24fb22dc445f3')
 
 pkgver() {
   cd $pkgname
@@ -53,39 +52,25 @@ prepare() {
   # https://bugs.archlinux.org/task/75649
   git apply -3 ../fusermount3.diff
 
-  git submodule init
-  git config --local submodule.libglnx.url "$srcdir/libglnx"
-  git config --local submodule.debugedit.url "$srcdir/debugedit"
-  git -c protocol.file.allow=always submodule update
-
-  NOCONFIGURE=1 ./autogen.sh
+  git submodule set-url subprojects/libglnx "$srcdir/libglnx"
+  git -c protocol.file.allow=always submodule update --init -- subprojects/libglnx
 }
 
 build() {
-  local configure_options=(
-    --prefix=/usr
-    --sysconfdir=/etc
-    --localstatedir=/var
-    --sbindir=/usr/bin
-    --libexecdir=/usr/lib
-    --disable-static
+  local meson_options=(
+    -D fuse=3
   )
 
-  cd $pkgname
-  ./configure "${configure_options[@]}"
-  sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
-  make
+  artix-meson $pkgname build "${meson_options[@]}"
+  meson compile -C build
 }
 
-# fails in jenkins; skip
-#check() {
-#  cd $pkgname
-#  make -k check
-#}
+check() {
+  meson test -C build --print-errorlogs ||: # skip failing tests
+}
 
 package() {
-  cd $pkgname
-  make DESTDIR="$pkgdir" install
+  meson install -C build --destdir "$pkgdir"
 }
 
 # vim:set sw=2 sts=-1 et:
