Updated apache-openrc - 20241206-1

diff --git a/world/apache-openrc/httpd.initd b/world/apache-openrc/httpd.initd
--- a/world/apache-openrc/httpd.initd
+++ b/world/apache-openrc/httpd.initd
@@ -1,41 +1,12 @@
 #!/usr/bin/openrc-run
-# Copyright 1999-2016 Gentoo Foundation
-# Distributed under the terms of the GNU General Public License v2
 
-extra_commands="configtest modules virtualhosts"
-extra_started_commands="configdump fullstatus graceful gracefulstop reload"
-
-description_configdump="Dumps the configuration of the runing apache server. Requires server-info to be enabled and www-client/lynx."
-description_configtest="Run syntax tests for configuration files."
-description_fullstatus="Gives the full status of the server. Requires lynx and server-status to be enabled."
-description_graceful="A graceful restart advises the children to exit after the current request and reloads the configuration."
-description_gracefulstop="A graceful stop advises the children to exit after the current request and stops the server."
-description_modules="Dump a list of loaded Static and Shared Modules."
-description_reload="Kills all children and reloads the configuration."
-description_virtualhosts="Show the settings as parsed from the config file (currently only shows the virtualhost settings)."
-description_stop="Kills all children and stops the server."
-
-# Apply default values for some conf.d variables.
-PIDFILE="${PIDFILE:-/run/httpd/httpd.pid}"
-TIMEOUT=${TIMEOUT:-15}
-SERVERROOT="${SERVERROOT:-/usr/lib/httpd}"
-CONFIGFILE="${CONFIGFILE:-/etc/httpd/conf/httpd.conf}"
-LYNX="${LYNX:-lynx -dump}"
-STATUSURL="${STATUSURL:-http://localhost/server-status}"
-RELOAD_TYPE="${RELOAD_TYPE:-graceful}"
-
-# Append the server root and configuration file parameters to the
-# user's APACHE2_OPTS.
-APACHE2_OPTS="${APACHE2_OPTS} -d ${SERVERROOT}"
-APACHE2_OPTS="${APACHE2_OPTS} -f ${CONFIGFILE}"
-
-# The path to the apache2 binary.
-APACHE2="/usr/bin/apachectl"
+extra_commands="configdump configtest modules virtualhosts"
+extra_started_commands="fullstatus graceful gracefulstop reload"
 
 depend() {
 	need net
-	use dns entropy logger mysql netmount postgresql
-	after sshd
+	use mysql dns logger netmount postgresql
+	after sshd firewall
 }
 
 configtest() {
@@ -45,21 +16,37 @@ configtest() {
 }
 
 checkconfd() {
+	PIDFILE="${PIDFILE:-/run/httpd/httpd.pid}"
+	TIMEOUT=${TIMEOUT:-10}
+
+	SERVERROOT="${SERVERROOT:-/usr/lib/httpd}"
 	if [ ! -d ${SERVERROOT} ]; then
 		eerror "SERVERROOT does not exist: ${SERVERROOT}"
 		return 1
 	fi
+
+	CONFIGFILE="${CONFIGFILE:-/etc/httpd/conf/httpd.conf}"
+	[ "${CONFIGFILE#/}" = "${CONFIGFILE}" ] && CONFIGFILE="${SERVERROOT}/${CONFIGFILE}"
+	if [ ! -r "${CONFIGFILE}" ]; then
+		eerror "Unable to read configuration file: ${CONFIGFILE}"
+		return 1
+	fi
+
+	HTTPD_OPTS="${HTTPD_OPTS} -d ${SERVERROOT}"
+	HTTPD_OPTS="${HTTPD_OPTS} -f ${CONFIGFILE}"
+	[ -n "${STARTUPERRORLOG}" ] && HTTPD_OPTS="${HTTPD_OPTS} -E ${STARTUPERRORLOG}"
+	return 0
+
 }
 
 checkconfig() {
-	checkpath --directory /run/httpd
 	checkconfd || return 1
 
-	OUTPUT=$( ${APACHE2} ${APACHE2_OPTS} -t 2>&1 )
+	${HTTPD} ${HTTPD_OPTS} -t 1>/dev/null 2>&1
 	ret=$?
 	if [ $ret -ne 0 ]; then
 		eerror "${SVCNAME} has detected an error in your setup:"
-		printf "%s\n" "${OUTPUT}"
+		${HTTPD} ${HTTPD_OPTS} -t
 	fi
 
 	return $ret
@@ -67,64 +54,40 @@ checkconfig() {
 
 start() {
 	checkconfig || return 1
+	checkpath --directory $(dirname $PIDFILE)
 
-	if [ -n "${STARTUPERRORLOG}" ] ; then
-		# We must make sure that we only append to APACHE2_OPTS
-		# in start() and not in stop() or anywhere else that may
-		# be executed along with start(), see bug #566726.
-		APACHE2_OPTS="${APACHE2_OPTS} -E ${STARTUPERRORLOG}"
-	fi
+	[ -f /var/log/httpd/ssl_scache ] && rm /var/log/httpd/ssl_scache
 
 	ebegin "Starting ${SVCNAME}"
-	# Use start stop daemon to apply system limits #347301 
-	start-stop-daemon --start -- ${APACHE2} ${APACHE2_OPTS} -k start
-
-	local i=0 retval=1
-	while [ $i -lt ${TIMEOUT} ] ; do
-		if [ -e "${PIDFILE}" ] ; then
-			retval=0
-			break
-		fi
-		sleep 1 && i=$(expr $i + 1)
-	done
-
-	eend ${retval}
+	start-stop-daemon --start \
+		--pidfile ${PIDFILE} \
+		--exec ${HTTPD} \
+		-- ${HTTPD_OPTS} -k start
+	eend $?
 }
 
 stop() {
-	if [ "${RC_CMD}" = "restart" ]; then
-		checkconfig || return 1
-	fi
-
-	PID=$(cat "${PIDFILE}" 2>/dev/null)
-	if [ -z "${PID}" ]; then
-		einfo "${SVCNAME} not running (no pid file)"
-		return 0
-	fi
+	checkconfd || return 1
 
 	ebegin "Stopping ${SVCNAME}"
-	${APACHE2} ${APACHE2_OPTS} -k stop
-
-	local i=0 retval=0
-	while ( test -f "${PIDFILE}" || pgrep -P ${PID} httpd >/dev/null ) \
-		&& [ $i -lt ${TIMEOUT} ]; do
-		sleep 1 && i=$(expr $i + 1)
-	done
-	[ -e "${PIDFILE}" ] && retval=1
-
-	eend ${retval}
+	start-stop-daemon --stop --pidfile ${PIDFILE} --exec ${HTTPD} \
+		--retry ${TIMEOUT}
+	eend $?
 }
 
 reload() {
+	RELOAD_TYPE="${RELOAD_TYPE:-graceful}"
+
 	checkconfig || return 1
+	service_started "${SVCNAME}" || return
 
 	if [ "${RELOAD_TYPE}" = "restart" ]; then
 		ebegin "Restarting ${SVCNAME}"
-		${APACHE2} ${APACHE2_OPTS} -k restart
+		${HTTPD} ${HTTPD_OPTS} -k restart
 		eend $?
 	elif [ "${RELOAD_TYPE}" = "graceful" ]; then
 		ebegin "Gracefully restarting ${SVCNAME}"
-		${APACHE2} ${APACHE2_OPTS} -k graceful
+		${HTTPD} ${HTTPD_OPTS} -k graceful
 		eend $?
 	else
 		eerror "${RELOAD_TYPE} is not a valid RELOAD_TYPE. Please edit /etc/conf.d/${SVCNAME}"
@@ -133,49 +96,59 @@ reload() {
 
 graceful() {
 	checkconfig || return 1
+	service_started "${SVCNAME}" || return
 	ebegin "Gracefully restarting ${SVCNAME}"
-	${APACHE2} ${APACHE2_OPTS} -k graceful
+	${HTTPD} ${HTTPD_OPTS} -k graceful
 	eend $?
 }
 
 gracefulstop() {
 	checkconfig || return 1
 	ebegin "Gracefully stopping ${SVCNAME}"
-	${APACHE2} ${APACHE2_OPTS} -k graceful-stop
+	start-stop-daemon --stop --pidfile ${PIDFILE} --exec ${HTTPD} \
+		--retry SIGWINCH/${TIMEOUT}
 	eend $?
 }
 
 modules() {
 	checkconfig || return 1
-	${APACHE2} ${APACHE2_OPTS} -M 2>&1
+
+	${HTTPD} ${HTTPD_OPTS} -M 2>&1
 }
 
 fullstatus() {
-	if ! command -v $(set -- ${LYNX}; echo $1) 2>&1 >/dev/null; then
-		eerror "lynx not found! you need to emerge www-client/lynx"
+	LYNX="${LYNX:-lynx -dump}"
+	STATUSURL="${STATUSURL:-http://localhost/server-status}"
+
+	if ! service_started "${SVCNAME}"; then
+		eerror "${SVCNAME} not started"
+	elif ! type -p $(set -- ${LYNX}; echo $1) 2>&1 >/dev/null; then
+		eerror "lynx not installed!"
 	else
 		${LYNX} ${STATUSURL}
 	fi
 }
 
 virtualhosts() {
-	checkconfig || return 1
-	${APACHE2} ${APACHE2_OPTS} -S
+	checkconfd || return 1
+	${HTTPD} ${HTTPD_OPTS} -S
 }
 
 configdump() {
+	LYNX="${LYNX:-lynx -dump}"
 	INFOURL="${INFOURL:-http://localhost/server-info}"
 
 	checkconfd || return 1
 
-	if ! command -v $(set -- ${LYNX}; echo $1) 2>&1 >/dev/null; then
-		eerror "lynx not found! you need to emerge www-client/lynx"
+	if ! service_started "${SVCNAME}"; then
+		eerror "${SVCNAME} not started"
+	elif ! type -p $(set -- ${LYNX}; echo $1) 2>&1 >/dev/null; then
+		eerror "lynx not installed!"
 	else
-		echo "${APACHE2} started with '${APACHE2_OPTS}'"
+		echo "${HTTPD} started with '${HTTPD_OPTS}'"
 		for i in config server list; do
 			${LYNX} "${INFOURL}/?${i}" | sed '/Apache Server Information/d;/^[[:space:]]\+[_]\+$/Q'
 		done
 	fi
 }
 
-# vim: ts=4 filetype=gentoo-init-d
