Updated aws-cli-v2 - 2.32.28-1

diff --git a/world/aws-cli-v2/PKGBUILD b/world/aws-cli-v2/PKGBUILD
--- a/world/aws-cli-v2/PKGBUILD
+++ b/world/aws-cli-v2/PKGBUILD
@@ -1,121 +1,141 @@
-# Maintainer: Chih-Hsuan Yen <yan12125@archlinux.org>
+# Maintainer: Carl Smedstad <carsme@archlinux.org>
+# Contributor: Chih-Hsuan Yen <yan12125@archlinux.org>
 # Contributor: Marcel Campello <marcel.campello@prafrentex.com.br>
 # Contributor: David Birks <david@birks.dev>
 
 pkgname=aws-cli-v2
-# https://github.com/aws/aws-cli/raw/v2/CHANGELOG.rst
-pkgver=2.15.19
+pkgver=2.32.28
 pkgrel=1
-pkgdesc='Unified command line interface for Amazon Web Services (version 2)'
-arch=(any)
-url='https://github.com/aws/aws-cli/tree/v2'
-license=(Apache)
-depends=(python python-awscrt python-certifi python-colorama python-cryptography python-dateutil
-         python-distro python-docutils python-jmespath python-prompt_toolkit python-ruamel-yaml
-         python-urllib3)
-makedepends=(python-build python-wheel python-flit-core python-installer)
-# Tests need the 'ps' binary
-checkdepends=(python-pytest python-pytest-xdist python-jsonschema procps-ng)
+pkgdesc='Universal Command Line Interface for Amazon Web Services (version 2)'
+arch=('any')
+url="https://docs.aws.amazon.com/cli"
+_url="https://github.com/aws/aws-cli"
+license=('Apache-2.0')
+depends=(
+  'python'
+  'python-awscrt'
+  'python-colorama'
+  'python-dateutil'
+  'python-distro'
+  'python-docutils'
+  'python-jmespath'
+  'python-prompt_toolkit'
+  'python-ruamel-yaml'
+  'python-urllib3'
+)
+makedepends=(
+  'git'
+  'python-build'
+  'python-flit-core'
+  'python-installer'
+  'python-wheel'
+)
+checkdepends=(
+  'python-jsonschema'
+  'python-pytest'
+  'python-pytest-xdist'
+)
 provides=(aws-cli)
 conflicts=(aws-cli)
-install=aws-cli-v2.install
-source=("https://awscli.amazonaws.com/awscli-$pkgver.tar.gz"{,.sig}
-        build-ac.index-in-tmp.diff
-        fix-env.diff
-        "$pkgname-tz-fix.patch"
-        "${pkgname}-ruamel-yaml-v4.patch"
-        allow-egg-info.diff
-        botocore-2922.patch
-        botocore-2924.patch
-        botocore-2990-rebased.patch)
-sha256sums=('4acf1cbb9bd7f158d13276f18467d9f8fd8dde504e537141fe8899b1273f9d5c'
-            'SKIP'
-            '0267e41561ab2c46a97ebfb024f0b047aabc9e6b9866f204b2c1a84ee5810d63'
-            '893d61d7e958c3c02bfa1e03bf58f6f6abd98849d248cc661f1c56423df9f312'
-            '4fc614b8550d7363bb2d578c6b49326c9255203eb2f933fd0551f96ed5fb1f30'
-            '20a9fcd5235bf606e86a6ec06ca30307ebbcfd36063d2ac561c1f9eff7243046'
-            '6768df8667fe7fd827e6eef1c4cdb3eae25aba5806bbc725270200a585f62152'
-            '62be6cad0f9039ae682abffd167181abbd4a690e2680867418c5542893d74b36'
-            'aad8b863d9f9107c56401e71d76b71f526efd9f8efac31e2a007b9071f85b5b6'
-            'a43c3e9aba8974fc09f1780a37b6a94108b15dbbbcecdf6d9e7e224ca135816b')
-validpgpkeys=(
-  'FB5DB77FD5C118B80511ADA8A6310ACC4672475C'  # the key mentioned on https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
+install=$pkgname.install
+source=(
+  "git+$_url#tag=$pkgver"
+  "https://github.com/boto/botocore/commit/f0ff061aebd9ef15a66f87b675789275e373da43.patch"
+  "$pkgname-python-prompt-toolkit-3.0.52-compat.patch"
+  "$pkgname-python-3.14-argparse-compat.patch"
 )
+b2sums=('fb5cd9b408bc00a235ee9b112ddd0d817b3d765e1d7ee13c00899a4ea01a8e8f3e6e272842a11b462dcad58bb854034867d8cfbaae7c3b7d24d5563b1e6c100a'
+        '34b49f02e77f5b0918df1ec61ba7076d6a795cb9d55708261aa6cfc2d065e4282c88ea6f4c40e0de6c7ca380056f527962cafc309ac9cc76e0286bcc1be6b409'
+        'e8a53aa1c524f38baedf8062e8ef5a8591e7eac053d52d772f3015debdb87100ffcb4974137a6cd0226f7709379de683ff1cff4c89a24c0c3a87f32541ccbca0'
+        'b11a980fd602f7ed61575677c4e75af7ce7784d9f3ff8ed4d7b9f7e830e8aae8780bbb27331f881d00d959469f7a35890725d1abc6e9d5f87b5ac632b3341ba6')
 
 prepare() {
-  cd awscli-$pkgver
+  cd ${pkgname%-v2}
+  # Remove deprecated `strict` poolmanager kwarg (#3036)
+  patch -Np1 -f -d awscli < ../f0ff061aebd9ef15a66f87b675789275e373da43.patch || :
+  patch -Np3 -f -d tests/unit/botocore < ../f0ff061aebd9ef15a66f87b675789275e373da43.patch || :
 
-  # Don't treat warnings as errors
-  sed -i '/"error::/d' pyproject.toml
-
-  # ac.index is an SQLite database, and building it on copy-on-write filesystems (ex: BTRFS) takes ages
-  patch -Np1 -i ../build-ac.index-in-tmp.diff
-
-  # Fix conflicts between tests/functional/test_clidriver.py::TestSession and tests/functional/botocore/leak/test_resource_leaks.py
-  patch -Np1 -i ../fix-env.diff
-
-  # Fix possible test failure with a non-UTC time zone (https://bugs.archlinux.org/task/77919)
-  patch -Np1 -i ../$pkgname-tz-fix.patch
-
-  # Fix tests with newer ruamel.yaml
-  # https://github.com/aws/aws-cli/pull/8072 (unmerged)
-  patch -Np1 -i ../${pkgname}-ruamel-yaml-v4.patch
-
-  # tests/dependencies checks dependencies, and many Arch Linux packages are not using PEP 517 yet
-  patch -Np1 -i ../allow-egg-info.diff
-
-  # Backport fixes for urllib3 2.x to vendored botocore
-  pushd awscli
-  # [Defer to system defaults for cipher suites with urllib3 2.0+](https://github.com/boto/botocore/pull/2922)
-  patch --no-backup-if-mismatch -Np1 -i ../../botocore-2922.patch
-  # [Do not set_ciphers(DEFAULT_CIPHERS) if DEFAULT_CIPHERS is None](https://github.com/boto/botocore/pull/2924)
-  patch --no-backup-if-mismatch -Np1 -i ../../botocore-2924.patch
-  # [Move 100-continue behavior to use high-level request interface](https://github.com/boto/botocore/pull/2990)
-  # Manually rebased due to conflicts from refactoring
-  patch --no-backup-if-mismatch -Np1 -i ../../botocore-2990-rebased.patch
-  popd
-
-  # use unittest.mock
-  # https://src.fedoraproject.org/rpms/awscli2/blob/rawhide/f/awscli2.spec
-  find -type f -name '*.py' -exec sed \
-      -e 's/^\( *\)import mock$/\1from unittest import mock/' \
-      -e 's/^\( *\)from mock import mock/\1from unittest import mock/' \
-      -e 's/^\( *\)from mock import/\1from unittest.mock import/' \
-      -i '{}' +
+  # Fix for python-prompt-toolkit 3.0.52
+  patch -Np1 -f < ../$pkgname-python-prompt-toolkit-3.0.52-compat.patch
+  # Fix Python 3.14 argparse compatibility
+  patch -Np1 -f < ../$pkgname-python-3.14-argparse-compat.patch
 }
 
 build() {
-  cd awscli-$pkgver
-
-  # flit-core adds runtime dependencies to reported build-time dependencies [1],
-  # and upstream often lags behind the latest dependencies [2], thus --skip-dependency-check
-  # [1] https://github.com/pypa/flit/issues/354
-  # [2] https://github.com/aws/aws-cli/issues/5943
+  cd ${pkgname%-v2}
   python -m build --wheel --no-isolation --skip-dependency-check
-  # Copy the built ac.index for tests
-  cp -v build/unpacked_wheel/awscli/data/ac.index awscli/data/ac.index
 }
 
 check() {
-  cd awscli-$pkgver
+  cd ${pkgname%-v2}
+  local pytest_args=(
+    -vv
+    --numprocesses=auto
 
-  export AWS_SECRET_ACCESS_KEY=fake_key
+    # Not relevant to test build back-end and dependency versions, plus these
+    # tests take forever and fills up /tmp.
+    --ignore=tests/backends
+    --ignore=tests/dependencies
+    # Takes forever (15+ minutes) to collect.
+    --ignore=tests/functional
+
+    # Depends on urllib3 internals and fails with urllib3 2.X.
+    --deselect=tests/unit/botocore/test_awsrequest.py::TestAWSHTTPConnection::test_expect_100_continue_returned
+    --deselect=tests/unit/botocore/test_awsrequest.py::TestAWSHTTPConnection::test_expect_100_sends_connection_header
+    --deselect=tests/unit/botocore/test_awsrequest.py::TestAWSHTTPConnection::test_expect_100_continue_sends_307
+    --deselect=tests/unit/botocore/test_awsrequest.py::TestAWSHTTPConnection::test_handles_expect_100_with_different_reason_phrase
+    --deselect=tests/unit/botocore/test_awsrequest.py::TestAWSHTTPConnection::test_expect_100_continue_no_response_from_server
+    --deselect=tests/unit/botocore/test_awsrequest.py::TestAWSHTTPConnection::test_state_reset_on_connection_close
+
+    # Fails with:
+    # FileNotFoundError: [Errno 2] No such file or directory: 'temp_creds.csv'
+    --deselect=tests/unit/customizations/configure/test_importer.py::TestConfigureImportCommand::test_csv_content_from_file_succeeds
+
+    # Calls AWS services and requires credentials.
+    --deselect=tests/integration/botocore/test_apigateway.py
+    --deselect=tests/integration/botocore/test_client.py
+    --deselect=tests/integration/botocore/test_cloudwatch.py
+    --deselect=tests/integration/botocore/test_cognito_identity.py
+    --deselect=tests/integration/botocore/test_credentials.py
+    --deselect=tests/integration/botocore/test_ec2.py
+    --deselect=tests/integration/botocore/test_elastictranscoder.py
+    --deselect=tests/integration/botocore/test_emr.py
+    --deselect=tests/integration/botocore/test_glacier.py
+    --deselect=tests/integration/botocore/test_rds.py
+    --deselect=tests/integration/botocore/test_route53.py
+    --deselect=tests/integration/botocore/test_s3.py
+    --deselect=tests/integration/botocore/test_session.py
+    --deselect=tests/integration/botocore/test_smoke.py
+    --deselect=tests/integration/botocore/test_sts.py
+    --deselect=tests/integration/botocore/test_waiters.py
+    --deselect=tests/integration/customizations/s3/test_filegenerator.py
+    --deselect=tests/integration/customizations/s3/test_plugin.py
+    --deselect=tests/integration/customizations/test_waiters.py
+    --deselect=tests/integration/customizations/test_waiters.py
+    --deselect=tests/integration/s3transfer
+    --deselect=tests/integration/test_assume_role.py
+    --deselect=tests/integration/test_cli.py
+    --deselect=tests/integration/test_ec2.py
+    --deselect=tests/integration/test_smoke.py::test_can_make_success_request
+
+    # Fails for some reason
+    --deselect=tests/integration/test_smoke.py::test_display_error_message
+
+    # Fails due to Python 3.14 reference counting changes.
+    --deselect=tests/unit/botocore/test_utils.py::test_lru_cache_weakref
+  )
   export AWS_ACCESS_KEY_ID=fake_id
-
-  export PYTHONPATH="$PWD"
-
-  # Install a temporary copy to a virtual environment, as tests/dependencies checks global site-packages
-  python -m venv --system-site-packages "$PWD/venv"
-  "$PWD/venv/bin/python" -m installer dist/*.whl
-
-  # * Use --dist=loadfile following upstream. The default --dist=load may cause test failures and is not faster
-  # * Disable backend tests - those tests check if aws-cli can be installed or not, and are not compatible with all kinds of environments
-  "$PWD/venv/bin/python" -m pytest tests -n auto --dist loadfile --ignore=tests/backends --ignore=tests/integration
+  export AWS_SECRET_ACCESS_KEY=fake_key
+  python -m venv --system-site-packages test-env
+  test-env/bin/python -m installer dist/*.whl
+  PATH="$PWD/test-env/bin:$PATH" \
+    test-env/bin/python -m pytest "${pytest_args[@]}"
 }
 
 package() {
-  cd awscli-$pkgver
+  cd ${pkgname%-v2}
   python -m installer --destdir="$pkgdir" dist/*.whl
-  install -Dm 644 LICENSE.txt "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
-  install -Dm 644 bin/aws_bash_completer "$pkgdir/usr/share/bash-completion/completions/aws"
+  install -vDm644 bin/aws_bash_completer "$pkgdir/usr/share/bash-completion/completions/aws"
+  rm -v "$pkgdir/usr/bin/aws.cmd"
+  rm -v "$pkgdir/usr/bin/aws_bash_completer"
 }
