Updated gnome-remote-desktop - 44.2-1

diff --git a/world/gnome-remote-desktop/PKGBUILD b/world/gnome-remote-desktop/PKGBUILD
--- a/world/gnome-remote-desktop/PKGBUILD
+++ b/world/gnome-remote-desktop/PKGBUILD
@@ -1,8 +1,8 @@
+# Maintainer: Fabian Bornschein <fabiscafe-at-mailbox-dot-org>
 # Maintainer: Jan Alexander Steffens (heftig) <heftig@archlinux.org>
-# Contributor: Fabian Bornschein <fabiscafe-cat-mailbox-dog-org>
 
 pkgname=gnome-remote-desktop
-pkgver=44.2
+pkgver=45.0
 pkgrel=1
 pkgdesc="GNOME Remote Desktop server"
 url="https://wiki.gnome.org/Projects/Mutter/RemoteDesktop"
@@ -15,14 +15,17 @@ depends=(
   fuse3
   glib2
   libdrm
+  libei
   libepoxy
   libfdk-aac
   libnotify
+  libpipewire
   libsecret
   libvncserver
   libxkbcommon
   pipewire
   tpm2-tss
+  wireplumber
 )
 makedepends=(
   asciidoc
@@ -31,14 +34,15 @@ makedepends=(
   meson
 )
 checkdepends=(
+  dbus-broker
+  libegl
   mutter
   python-dbus
   python-gobject
-  wireplumber
+  pipewire-alsa
 )
 groups=(gnome)
-options=(debug)
-_commit=9d1ee9c9458636dbe4d3326dceec81dfefef56dd  # tags/44.2^0
+_commit=a7c4f2dd87fe09389dd93268b0ce3e32a6ceb6eb  # tags/45.0^0
 source=("git+https://gitlab.gnome.org/GNOME/gnome-remote-desktop.git#commit=$_commit")
 b2sums=('SKIP')
 
@@ -53,47 +57,16 @@ prepare() {
 
 build() {
   local meson_options=(
-    -D vnc=true
     -D systemd=false
+    -D vnc=true
   )
 
   artix-meson $pkgname build "${meson_options[@]}"
   meson compile -C build
 }
 
-_check() (
-  export XDG_CONFIG_HOME="$PWD/config-dir" XDG_RUNTIME_DIR="$PWD/runtime-dir"
-  mkdir -p -m 700 "$XDG_CONFIG_HOME" "$XDG_RUNTIME_DIR"
-
-  export GSETTINGS_SCHEMA_DIR="$PWD/build/src" GSETTINGS_BACKEND=keyfile
-  glib-compile-schemas "$GSETTINGS_SCHEMA_DIR"
-
-  openssl req -new -newkey rsa:4096 -days 720 -nodes -x509 \
-    -subj /C=DE/ST=NONE/L=NONE/O=GNOME/CN=gnome.org \
-    -keyout tls.key -out tls.crt
-
-  gsettings set org.gnome.desktop.remote-desktop.rdp tls-cert "$PWD/tls.crt"
-  gsettings set org.gnome.desktop.remote-desktop.rdp tls-key "$PWD/tls.key"
-  gsettings set org.gnome.desktop.remote-desktop.rdp screen-share-mode extend
-  gsettings set org.gnome.desktop.remote-desktop.rdp enable true
-  gsettings set org.gnome.desktop.remote-desktop.vnc enable true
-
-  pipewire &
-  _p1=$!
-
-  wireplumber &
-  _p2=$!
-
-  trap "kill $_p1 $_p2; wait" EXIT
-
-  export TCTI=tabrmd:bus_type=session
-
-  meson test -C build --print-errorlogs -t 3
-)
-
 check() {
-  # test fails
-  dbus-run-session bash -c "$(declare -f _check); _check" || :
+  meson test -C build --print-errorlogs -t 3 ||: # test fails skip
 }
 
 package() {
