Updated tigervnc-openrc - 20240818-1

diff --git a/world/tigervnc-openrc/tigervnc.initd b/world/tigervnc-openrc/tigervnc.initd
--- a/world/tigervnc-openrc/tigervnc.initd
+++ b/world/tigervnc-openrc/tigervnc.initd
@@ -1,6 +1,19 @@
-#!/usr/bin/openrc-run
-# Copyright 1999-2014 Gentoo Foundation
+#!/sbin/openrc-run
+# Copyright 1999-2022 Gentoo Authors
 # Distributed under the terms of the GNU General Public License, v2 or later
+
+# shellcheck shell=sh
+
+# Create symlinks for all displays.
+# For example for display :1, run `ln -s tigervnc /etc/init.d/tigervnc.1`
+# Then `rc-update add tigervnc.1 default`
+# For compatibility, /etc/init.d/tigervnc will start all displays.
+
+DISPLAYS=${SVCNAME#*.}
+if [ "$DISPLAYS" = "tigervnc" ]; then
+	should_warn=1
+	DISPLAYS=$(grep -v "^#" /etc/tigervnc/vncserver.users | sed -e 's/=.*//' -e 's/^://')
+fi
 
 depend() {
 	need net
@@ -8,62 +21,67 @@ depend() {
 
 checkconfig() {
 	if [ -n "${DISPLAYS}" ]; then
-		if [ $1 = "start" ]; then
-			local user
-			for user in $DISPLAYS; do
-				if eval [ ! -f "~${user%%:*}/.vnc/passwd" ]; then
-					eerror "There are no passwords defined for user ${user%%:*}."
+		if [ "$1" = "start" ]; then
+			for display in $DISPLAYS; do
+				user="$(grep "^:${display}" /etc/tigervnc/vncserver.users)"
+				user=${user#*=}
+				if [ -z "${user}" ]; then
+					eerror "User is not defined for display :${display} in /etc/tigervnc/vncserver.users"
 					return 1
-				elif [ -e "/tmp/.X11-unix/X${user##*:}" ]; then
-					eerror "Display :${user##*:} appears to be already in use because of /tmp/.X11-unix/X${user##*:}"
-					eerror "Remove this file if there is no X server $HOSTNAME:${user##*:}"
+				elif [ -e "/tmp/.X11-unix/X${display}" ]; then
+					eerror "Display :${display} appears to be already in use because of /tmp/.X11-unix/X${display}"
+					eerror "Remove this file if there is no X server for :${display}"
 					return 1
-				elif [ -e "/tmp/.X${user##*:}-lock" ]; then
-					eerror "Display :${user##*:} appears to be already in use because of /tmp/.X${user##*:}-lock"
-					eerror "Remove this file if there is no X server $HOSTNAME:${user##*:}"
+				elif [ -e "/tmp/.X${display}-lock" ]; then
+					eerror "Display :${display} appears to be already in use because of /tmp/.X${display}-lock"
+					eerror "Remove this file if there is no X server for :${display}"
 					return 1
+				# bug #690046
+				# The default config directory is now ~/.config/tigervnc, but still supports ~/.vnc if not found
+				# Only warn if password is missing, do not error out.  See bug #936442
+				elif ! runuser -l "${user}" -s /bin/bash -c \
+					"[[ ( -d ${XDG_CONFIG_HOME:-~/.config}/tigervnc && -f ${XDG_CONFIG_HOME:-~/.config}/tigervnc/passwd ) || ( ! -d ${XDG_CONFIG_HOME:-~/.config}/tigervnc && -f ~/.vnc/passwd ) ]]"; then
+					ewarn "There are no passwords defined for user ${user}. The server may not start."
 				fi
+				FREEDISPLAYS="${FREEDISPLAYS} ${display}"
 			done
 		fi
 		return 0
 	else
-		eerror 'Please define $DISPLAYS in /etc/conf.d/tigervnc'
+		eerror 'There are no displays configured in /etc/tigervnc/vncserver.users'
 		return 1
 	fi
 }
 
+checkwarn() {
+	if [ "${should_warn}" = "1" ]; then
+		ewarn 'Running /etc/init.d/tigervnc in compatibility mode'
+		ewarn 'Please migrate to one service per display as detailed here:'
+		ewarn 'https://wiki.gentoo.org/wiki/TigerVNC#Migrating_from_1.13.1-r2_or_lower:'
+	fi
+}
+
 start() {
+	checkwarn
+	FREEDISPLAYS=""
 	checkconfig start || return 1
-	ebegin "Starting TigerVNC server"
-	for user in $DISPLAYS; do
-		usrname=${user%%:*}
-		usropts=VNC_OPTS_${usrname}
-		usrdisp=${user##*:}
-		usrvar=$usropts"["$usrdisp"]"
-		[ -z ${!usrvar} ] && vnc_opts=$VNC_OPTS || vnc_opts=${!usrvar}
-
-		# A user may have an invalid shell, so we default to /bin/sh if its the case
-		if [ -x /usr/bin/getent ] ; then
-			usrshell=`getent passwd ${user%%:*} | cut -d: -f 7`
-			case "$usrshell" in
-				*/bash|*/ksh|*/sh|*/csh|*/tcsh) ;;          
-				*) shell="-s /bin/sh" ;;
-			esac
-			echo $usrshell $shell
-		fi
-
-		su ${shell} ${user%%:*} -c "source /etc/profile && cd ~${user%%:*} && vncserver :${user##*:} $vnc_opts" &>/dev/null
+	for display in $FREEDISPLAYS; do
+		[ -n "${TIGERVNC_XSESSION_FILE}" ] && export TIGERVNC_XSESSION_FILE
+		ebegin "Starting TigerVNC server :${display}"
+		start-stop-daemon --start --pidfile=/run/vncsession-":${display}".pid /usr/libexec/vncsession-start -- ":${display}"
+		eend $?
 	done
-	eend $?
 }
 
 stop() {
 	checkconfig stop || return 2
-	ebegin "Stopping TigerVNC server"
-	for user in $DISPLAYS; do
-		su -s /bin/sh ${user%%:*} -c "vncserver -kill :${user##*:}" &>/dev/null
+	for display in $DISPLAYS; do
+		ebegin "Stopping TigerVNC server :${display}"
+		start-stop-daemon --stop --pidfile=/run/vncsession-":${display}".pid
+		eend $?
 	done
-	eend $?
+	# Do not fail if a server is missing
+	/bin/true
 }
 
 restart() {
